### ISSUE TITLE
AI difficulty shows up as Elite when not elite

### ISSUE THREAD

**Issue by eric-hu** [dsjoerg/esdb#3]
I thought I noticed this last month, was just chatting with a friend and he ran into this issue too.  Will post a link once I hear back from him.

**Comment by dsjoerg** [comment]
Yes, this is a side-effect of all AI players being mapped to the same ESDB identity.  In order to fix it, I think the easiest way is to establish multiple ESDB::Identity objects, one for each AI level, and then change the identity-mapping code accordingly.

**Comment by eric-hu** [comment]
Just revisiting this issue since I've had it as a to-do to investigate this, but I don't think I'll have time any time soon.  Feel free to close this issue if you'd like to.

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#10
